# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1343458312);
user_pref("app.update.lastUpdateTime.background-update-timer", 1343458552);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1343458432);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1343458192);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 1048576);
user_pref("browser.migration.version", 6);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage_override.buildID", "20120713134347");
user_pref("browser.startup.homepage_override.mstone", "14.0.1");
user_pref("browser.syncPromoViewsLeft", 1);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"firebug@software.joehewitt.com\":{\"version\":\"1.10.0\",\"type\":\"extension\",\"descriptor\":\"D:\\\\develop\\\\twitter_searcher\\\\properties\\\\ff_profile\\\\extensions\\\\firebug@software.joehewitt.com.xpi\"}}");
user_pref("extensions.databaseSchema", 12);
user_pref("extensions.enabledAddons", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:14.0.1");
user_pref("extensions.firebug.addonBarOpened", true);
user_pref("extensions.firebug.currentVersion", "1.10.0");
user_pref("extensions.firebug.framePosition", "detached");
user_pref("extensions.firebug.previousPlacement", 3);
user_pref("extensions.firebug.toolbarCustomizationDone", true);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1343457612758}}},{\"name\":\"app-profile\",\"addons\":{\"firebug@software.joehewitt.com\":{\"descriptor\":\"D:\\\\develop\\\\twitter_searcher\\\\properties\\\\ff_profile\\\\extensions\\\\firebug@software.joehewitt.com.xpi\",\"mtime\":1343459208312}}}]");
user_pref("extensions.lastAppVersion", "14.0.1");
user_pref("extensions.lastPlatformVersion", "14.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gfx.direct3d.prefer_10_1", true);
user_pref("idle.lastDailyNotification", 1343458456);
user_pref("intl.charsetmenu.browser.cache", "windows-1251, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1343458456);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1343458456);
user_pref("toolkit.startup.last_success", 1343547114);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("toolkit.telemetry.rejected", true);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1346050078);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
